require qt5module.inc

LICENSE = "GFDL-1.3 & LGPL-2.1 & PREVIEW.COMMERCIAL"
LIC_FILES_CHKSUM ?= "file://LICENSE.LGPL;md5=4ac745f4b16b419fa48a24d41e983c40 \
                     file://LGPL_EXCEPTION.txt;md5=eb6c371255e1262c55ae9b652a90b528 \
                     file://LICENSE.PREVIEW.COMMERCIAL;md5=9d94dadfab8b246782ffea02082ee13a \
                     file://LICENSE.FDL;md5=f70ee9a6c44ae8917586fea34dff0ab5"

INC_PR = "r1"
