require qt5.inc

DEPENDS += "qtdeclarative qtwebsockets"

# There are no LGPLv3-only licensed files in this component.
# There are no GPLv2 licensed files in this component.
LIC_FILES_CHKSUM = "file://LICENSE.FDL;md5=6d9f2a9af4c8b8c3c769f6cc1b6aaf7e \
                    file://LICENSE.GPLv2;md5=e782f55badfa137e5e59c330f12cc8ed \
                    file://LICENSE.LGPLv21;md5=cff17b12416c896e10ae2c17a64252e7 \
                    file://LICENSE.LGPLv3;md5=c1939be5579666be947371bc8120425f \
"
