require qt5.inc

DEPENDS += "qtbase qtdeclarative"

LICENSE = "GFDL-1.3 & (LGPL-2.1 & Digia-Qt-LGPL-Exception-1.1 | LGPL-3.0)"
LIC_FILES_CHKSUM = "file://LICENSE;md5=4fbd65380cdd255951079008b364516c \
                    file://LICENSE.GPLv2;md5=e782f55badfa137e5e59c330f12cc8ed \
                    file://LICENSE.LGPLv3;md5=c1939be5579666be947371bc8120425f \
                    file://LICENSE.LGPLv21;md5=cff17b12416c896e10ae2c17a64252e7 \
"
